import pandas as pd
import json
from datetime import datetime
from core.config import BRONZE_DIR, SILVER_DIR
from core.audit import log_action, log_error
from core.state import update_step_status

def load_sttm_rules() -> dict:
    """Loads the STTM rules generated by the AI."""
    sttm_path = BRONZE_DIR / "sttm_rules.json"
    if not sttm_path.exists():
        raise FileNotFoundError(f"STTM rules not found at {sttm_path}. Please run sttm_generator_agent.py first.")
    with open(sttm_path, "r") as f:
        return json.load(f)

def clean_data(df: pd.DataFrame, file_name: str, silver_rules: dict) -> pd.DataFrame:
    """Applies basic data cleaning and standardization rules based on STTM instructions."""
    df_cleaned = df.copy()
    
    # 1. Identify which entity rules apply based on the file name
    entity_key = ""
    if "sales" in file_name.lower():
        entity_key = "sales"
        primary_key = "transaction_id" if "transaction_id" in df_cleaned.columns else None
    elif "product" in file_name.lower():
        entity_key = "products"
        primary_key = "product_id" if "product_id" in df_cleaned.columns else None
    elif "store" in file_name.lower():
        entity_key = "stores"
        primary_key = "store_id" if "store_id" in df_cleaned.columns else None
    else:
        primary_key = None

    # 2. Handle duplicates if a primary key was identified
    if primary_key:
        initial_count = len(df_cleaned)
        df_cleaned = df_cleaned.drop_duplicates(subset=[primary_key])
        dropped = initial_count - len(df_cleaned)
        if dropped > 0:
            log_action("SilverAgent", f"Removed {dropped} duplicate rows from {file_name}")

    # 3. Fill null values with sensible defaults based on column types
    for col in df_cleaned.columns:
        if df_cleaned[col].isnull().sum() > 0:
            if df_cleaned[col].dtype in ['int64', 'float64']:
                df_cleaned[col] = df_cleaned[col].fillna(0)
            else:
                df_cleaned[col] = df_cleaned[col].fillna("Unknown")
            log_action("SilverAgent", f"Imputed missing values in column '{col}' for {file_name}")

    # 4. Standardize any date columns to ISO format strings
    for col in df_cleaned.columns:
        if 'date' in col.lower() or 'time' in col.lower():
            try:
                # Exclude metadata timestamp column
                if col != "bronze_ingested_at":
                    df_cleaned[col] = pd.to_datetime(df_cleaned[col]).dt.strftime('%Y-%m-%d')
            except Exception:
                pass # Skip if column cannot be converted to date
                
    return df_cleaned

def process_to_silver():
    """Reads Bronze data, applies STTM cleaning rules, and saves clean Parquet files to the Silver layer."""
    log_action("SilverAgent", "Starting Silver cleaning process")
    
    try:
        rules = load_sttm_rules()
        silver_rules = rules.get("silver", {})
    except Exception as e:
        log_error("SilverAgent", f"Failed to load cleaning rules: {str(e)}")
        print("⚠️ Missing STTM rules. Please make sure sttm_generator_agent.py has completed successfully.")
        return

    bronze_files = list(BRONZE_DIR.glob("*.parquet"))
    if not bronze_files:
        log_error("SilverAgent", "No Bronze Parquet files found to clean.")
        print("⚠️ No Bronze files found. Please run bronze_agent.py first.")
        return

    SILVER_DIR.mkdir(parents=True, exist_ok=True)
    clean_files = []

    for file_path in bronze_files:
        try:
            print(f"🥈 Cleaning and standardizing {file_path.name} to Silver...")
            
            # Read Bronze Parquet file
            df = pd.read_parquet(file_path)
            
            # Clean data using rules
            df_cleaned = clean_data(df, file_path.name, silver_rules)
            
            # Add Silver metadata
            df_cleaned["silver_processed_at"] = datetime.utcnow().isoformat()
            
            # Save clean file to Silver
            output_path = SILVER_DIR / file_path.name
            df_cleaned.to_parquet(output_path, index=False)
            clean_files.append(str(output_path))
            
            log_action("SilverAgent", "Cleaned file successfully", f"{file_path.name} saved to Silver")
            
        except Exception as e:
            log_error("SilverAgent", f"Failed to process {file_path.name}: {str(e)}")
            raise e

    log_action("SilverAgent", "Completed Silver cleaning", f"Cleaned {len(clean_files)} files.")
    update_step_status("silver", "completed", clean_files)
    print(f"✅ Silver layer cleaning complete! Files saved in: {SILVER_DIR}")

if __name__ == "__main__":
    process_to_silver()
